services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command:  tunnel --no-autoupdate --credentials-file /run/secrets/tunnel_token run ${TUNNEL_ID}
    restart: always
    secrets:
      - tunnel_token
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: TRUE
      VERSION: "1.20.4"
      DIFFICULTY: hard
      INIT_MEMORY: 2G
      MAX_MEMORY: 8G
    volumes:
      - ./data:/data
secrets:
  tunnel_token:
    external: ./secrets/tunnel.json
